config/routes.rb
Handpickedoha::Application.routes.draw do
  get ENV['RAILS_RELATIVE_URL_ROOT'] => 'front#index' if ENV['RAILS_RELATIVE_URL_ROOT']
  root :to => 'front#index'
  get 'users/:id/reset_password_from_email/:key' => 'users#reset_password', :as => 'reset_password_from_email'
  get 'users/:id/accept_invitation_from_email/:key' => 'users#accept_invitation', :as => 'accept_invitation_from_email'
  get 'users/:id/activate_from_email/:key' => 'users#activate', :as => 'activate_from_email'
  post 'search' => 'front#search', :as => 'site_search_post'
  get 'search' => 'front#search', :as => 'site_search'
  get 'users/my_favorites' => 'users#my_favorites', :as => 'my_favorites'

  resources :providers do
    member do
      get "up_down_vote", to: "providers#up_down_vote"
      get "like", to: "providers#upvote"
      get "dislike", to: "providers#downvote"
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  hobo_model # Don't put anything above this

  fields do
    name :string, :required, :unique
    timestamps
  end
  attr_accessible :name
  has_many :services
  children :services

  # --- Permissions --- #

  def create_permitted?
    acting_user.administrator?
  end

  def update_permitted?
    acting_user.administrator?
  end

  def destroy_permitted?
    acting_user.administrator?
  end

  def view_permitted?(field)
    true
  end

end

app/models/guest.rb
class Guest < Hobo::Model::Guest

  def administrator?
    false
  end

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  acts_as_votable
  hobo_model # Don't put anything above this

  has_many :votes, :as => :votable


  fields do
    name        :string, :required
    description :text,   :required
    website     :string
    pricerange  :string
    rating      :string
    imageurl    :string
    timestamps
  end
  attr_accessible :name, :description, :website, :pricerange, :rating, :service, :service_id, :imageurl

  belongs_to :service

  # --- Permissions --- #

  def create_permitted?
    acting_user.administrator?
  end

  def update_permitted?
    acting_user.administrator?
  end

  def destroy_permitted?
    acting_user.administrator?
  end

  def view_permitted?(field)
    true
  end


end

app/models/service.rb
class Service < ActiveRecord::Base

  hobo_model # Don't put anything above this

  fields do
    name        :string, :required, :unique
    description :text
    imageurl    :string
    timestamps
  end

  attr_accessible :name, :description, :category, :category_id, :imageurl

  belongs_to :category
  has_many  :providers
  children  :providers

  
  # --- Permissions --- #

  def create_permitted?
    acting_user.administrator?
  end

  def update_permitted?
    acting_user.administrator?
  end

  def destroy_permitted?
    acting_user.administrator?
  end

  def view_permitted?(field)
    true
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  hobo_user_model # Don't put anything above this
  has_many :votes ,:class_name=>"Vote",:foreign_key => :voter_id

  fields do
    name          :string, :required, :unique
    email_address :email_address, :login => true
    administrator :boolean, :default => false
    timestamps
  end
  attr_accessible :name, :email_address, :password, :password_confirmation, :current_password

  # This gives admin rights and an :active state to the first sign-up.
  # Just remove it if you don't want that
  before_create do |user|
    if !Rails.env.test? && user.class.count == 0
      user.administrator = true
      user.state = "active"
    end
  end


  # --- Signup lifecycle --- #

  lifecycle do

    state :active, :default => true

    create :signup, :available_to => "Guest",
           :params => [:name, :email_address, :password, :password_confirmation],
           :become => :active

    transition :request_password_reset, { :active => :active }, :new_key => true do
      UserMailer.forgot_password(self, lifecycle.key).deliver
    end

    transition :reset_password, { :active => :active }, :available_to => :key_holder,
               :params => [ :password, :password_confirmation ]

  end

  # --- Permissions --- #

  def create_permitted?
    # Only the initial admin user can be created
    self.class.count == 0
  end

  def update_permitted?
    acting_user.administrator? ||
      (acting_user == self && only_changed?(:email_address, :crypted_password,
                                            :current_password, :password, :password_confirmation))
    # Note: crypted_password has attr_protected so although it is permitted to change, it cannot be changed
    # directly from a form submission.
  end

  def destroy_permitted?
    acting_user.administrator?
  end

  def view_permitted?(field)
    true
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
	# belongs_to :provider ,:class_name=>"Vote",:foreign_key => :votable_id

	belongs_to :votable, :polymorphic => true
	belongs_to :provider,:class_name=>"Provider",:foreign_key => :votable_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  hobo_model_controller

  auto_actions :all

end

app/controllers/front_controller.rb
class FrontController < ApplicationController

  hobo_controller

  def index; end

  def summary
    if !current_user.administrator?
      redirect_to user_login_path
    end
  end

  def search
    if params[:query]
      site_search(params[:query])
    end
  end

end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController

  hobo_model_controller

  auto_actions :all
  auto_actions_for :service, :create

  def up_down_vote
	  @provider = Provider.find(params[:id])
	  find_or_create_like_unlike @provider
	  render :layout => false
	  # redirect_to service_path(@provider.service)
	end

	def upvote
		@provider = Provider.find(params[:id])
		unless @provider.votes.where(:voter_id =>current_user.id,:vote_flag => true).blank?
	  	@provider.vote_by :voter => current_user, :vote => 'bad'
	  else
	  	@provider.vote_by :voter => current_user, :vote => 'like'
	  end
	  render :layout => false
	end

	def downvote
    @provider = Provider.find(params[:id])
	  @provider.vote_by :voter => current_user, :vote => 'bad'
	  render :layout => false
	end

	def find_or_create_like_unlike provider
		# binding.pry
		unless provider.votes.where(:voter_id =>current_user.id,:vote_flag => true).blank?
	  	provider.vote_by :voter => current_user, :vote => 'bad'
	  else
	  	provider.vote_by :voter => current_user, :vote => 'like'
	  end
	end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  hobo_model_controller

  auto_actions :all
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  hobo_user_controller

  auto_actions :all, :except => [ :index, :new, :create]
  

  # Normally, users should be created via the user lifecycle, except
  #  for the initial user created via the form on the front screen on
  #  first run.  This method creates the initial user.
  def create
    hobo_create do
      if valid?
        self.current_user = this
        flash[:notice] = t("hobo.messages.you_are_site_admin", :default=>"You are now the site administrator")
        redirect_to home_page
      end
    end
  end

  def my_favorites
    unless current_user.class == Guest
      @providers = Vote.where(:voter_id =>current_user.id,:vote_flag => true).map(&:provider)
      render :layout => "erb_layout"
    else
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Handpickedoha</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/erb_layout.html.erb
<!DOCTYPE html>  <html lang="en">
    <head>      <title>Services : Handpickedoha</title>
      
  <link class="app-stylesheet" href="/assets/front.css" media="screen" rel="stylesheet">

      
      <script src="/assets/front.js"></script>
<script type="text/javascript"></script><meta content="width=device-width, initial-scale=1.0" name="viewport">      <meta content="authenticity_token" name="csrf-param">
<meta content="5b/LjIXqlfk/taXFZZedlDOXU9o+Of6gRZ1ysaGO8mo=" name="csrf-token">
</head>
<body>
	<div id="ajax-progress-wrapper">
		<div class="ajax-progress" id="ajax-progress">
			<div>
	      <span id="ajax-progress-text"></span>
			</div>
		</div>
	</div>
	<div class="navbar">
		<div class="navbar-inner navbar-innner">
		  <div class="header container">
		  	<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse" href="#">
		  	  <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
				</a>
				<div class="app-name">
				  <a class="brand" href="/">Handpickedoha</a>
				</div>
				<ul class="navigation main-nav nav">
				  <li class="">
				    <a href="/">Home</a>
					</li>
    			<li class="">
    			  <a class="class-link" href="/categories" rel="nofollow">Categories</a>
					</li>
    			<li class="">
    			  <a class="class-link" href="/providers" rel="nofollow">Providers</a>
					</li>
  				<li >
  				  <a class="class-link" href="/services" rel="nofollow">Services</a>
					</li>
    			<li class="active"><a href="/users/my_favorites">My Favorites</a></li>
				</ul>
				<div class="nav-collapse collapse">
					<ul class="navigation account-nav nav pull-right">
					  <li class="search">
					  	<div class="search" data-rapid="{&quot;live-search&quot;: {}}">
					  	  <form action="/search" class="form-search" data-rapid="{&quot;form&quot;:{&quot;ajax_attrs&quot;:{&quot;refocus-form&quot;:true,&quot;update&quot;:&quot;search-results-part&quot;,&quot;message&quot;:&quot;Querying...&quot;}}}" method="post" remove-class="form-horizontal">
					  	  	<div class="hidden-fields">
					  	  		<input id="page_path" name="page_path" type="hidden" value="/services">
					  	  		<input name="authenticity_token" type="hidden" value="5b/LjIXqlfk/taXFZZedlDOXU9o+Of6gRZ1ysaGO8mo=">
				  	  		</div>
				  	  		<input name="search_version" type="hidden" value="2">
				  	  		<input class="live-search search-query" name="query" placeholder="Search" type="search">
      						<i class="icon-search"></i>
      					</form>
      		    	<div class="part-wrapper" id="search-results-part">
    						</div>
							</div>
						</li>
      			<li class="dev-user-changer">
      				<select class="dev-user-changer" onchange="location.href = '/dev/set_current_user?login=' + encodeURIComponent(this.options[this.selectedIndex].value)">
      					<option value="">Guest</option>
      					<%User.all.each do |user|%>
    							<option <%= current_user ? 'selected="selected"' : ""%> value="<%=current_user.email_address%>"><%=current_user.email_address%></option>
    						<%end%>
							</select>
						</li>
						<% if current_user%>
	        		<li class="nav-item logged-in-as">
	        			<a class="user-link" href="/users/<%=current_user.id%>-<%=current_user.name%>" rel="nofollow">Logged in as <span class="view user-name "><%= current_user ? current_user.name : ""%></span></a>
	        		</li>        		
	        		<li class="nav-item account"><a class="user-link" href="/users/<%=current_user.id%>-<%=current_user.name%>/account" rel="nofollow">Account</a></li>
	        		<li class="nav-item log-out"><a href="/logout">Log out</a></li>
						<%end%>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="container bootstrap-content">
		<div class="row main-row">
			<div class="span12 main-column">
				<div class="section with-flash content">
				  <div class="section main-content">
				    <div class="header content-header well">
							<a class="btn pull-right btn-primary new-link new-service-link" href="/services/new" rel="nofollow">        New Service
							</a>
							<h2 class="heading">Service Index</h2>
						</div>
					<div class="section content-body"> 
						<%= yield %>
					</div>
				</div>
			</div>
		</div>
	</div>

</body>
</html>

app/views/providers/downvote.js.erb
$("#vote_count").html("<%=@provider.get_upvotes.size%>")

app/views/providers/up_down_vote.js.erb
$("#vote_count").html("<%=@provider.get_upvotes.size%>")

app/views/providers/upvote.js.erb
$("#vote_count").html("<%=@provider.get_upvotes.size%>")

app/views/taglibs/_vote.html.erb
<% if current_user.voted_for?(@post) %>

<p>
	<strong>Vote:</strong>
	<%= link_to "downvote", unlike_post_path(@post), class: "downvote", method: :put, remote: true %>
</p>

<% else %>

<p>
	<strong>Vote:</strong>
	<%= link_to "upvote", like_post_path(@post), class: "upvote", method: :put, remote: true %>
</p>

<% end %>

app/views/users/my_favorites.html.erb
<table class="table table-striped table-bordered collection">
	<thead>
		<tr class="field-heading-row">
		  <th class="Service-heading">Name</th>
      <th class="description-heading">Description</th>
      <th class="imageurl-heading">Website</th>   
		</tr>
	</thead>
	<tbody>
	<%@providers.each do |provider|%>
		<tr>
			<td><%=provider.name%></td>
			<td><%=provider.description%></td>
			<td><%=provider.website%></td>
		</tr>
	<%end%>
	</tbody>
</table>